### PR TITLE
fix: resolved dependency clash

### PR DESCRIPTION
**Pull request by BenTenmann**
numba requires numpy<=1.20

### CODE REVIEW

**Comment by grst** [comment]
Hi @BenTenmann, 

thanks for the PR! Did you get an error during installation? 

I believe in principle this should not be necessary, as pip should figure out transitive dependencies by itself (i.e. scirpy requires numba, numba requires numpy < 1.20, so it won't install a more recent version of numpy)

**Comment by BenTenmann** [comment]
Hi @grst 
No problem! Yes, in fact I did get an error when `pip` installing using a `python==3.8.2` environment, with a dependecy clash between `numba` and `numpy`.

**Comment by grst** [comment]
Interesting... out of curiosity: Did you install scirpy into a clean environment, or was there maybe a more recent version of numpy already installed?

**Comment by BenTenmann** [comment]
There was a more recent version of `numpy` (1.21.5) installed, hence the conflict.

**Comment by grst** [comment]
Either way, guess this can't harm.

**Pull request merged**
